### ISSUE TITLE
NOVEMBER ONLINE SCHEDULING

### ISSUE THREAD

**Issue by Robinmcgvr** [Robinmcgvr/Online-Scheduling#1]
Hi Lynne and Jonathan,

I have set up this new repository so we can keep track of the Online Scheduling progress going forwards.
This is also where we can log any issues/delays related to online scheduling.

**Comment by Robinmcgvr** [comment]
Countries complete as of 02/01/2020:
Australia
Spain

**Comment by Robinmcgvr** [comment]
Countries complete as of 05/01/2021
Brazil
Mexico

**Comment by Lynne12** [comment]
France complete

**Comment by Lynne12** [comment]
Austria complete

**Comment by Lynne12** [comment]
Hong Kong complete

**Comment by Lynne12** [comment]
Portugal complete

**Comment by Robinmcgvr** [comment]
To recap Countries completed as of 18/01/2021 are as follows:
Australia
Japan
Brazil
Mexico
France
Austria
Hong Kong
Portugal

**Comment by Lynne12** [comment]
Germany & Hungary complete

**Comment by Lynne12** [comment]
@Robinmcgvr a suggestion for this going forward is that you have each country listed in the first comment of the issue, with a check box next to it.  I could then check the box as the country is complete.  It would save the recaps and need for me to type multiple comments.  See below.  This is ordered as per the country priority list that you previously gave me.  You can see at a glance which countries are outstanding.

**Comment by Lynne12** [comment]
**Countries complete:-**

- [x] AUSTRALIA
- [x] NEW ZEALAND
- [x] BRAZIL
- [x] MEXICO
- [x] HONG KONG
- [x] FRANCE
- [x] IRELAND
- [x] PORTUGAL
- [x] SWITZERLAND
- [x] SPAIN
- [x] SWEDEN
- [x] AUSTRIA
- [x] GERMANY
- [x] HUNGARY
- [x] CZECH REPUBLIC
- [x] BELGIUM
- [x] GREECE
- [x] CROATIA
- [x] ROMANIA
- [x] SERBIA
- [x] NETHERLANDS

**Comment by Robinmcgvr** [comment]
Greece - Nova Cinema 1 (ishow.gr)
Data missing and lost for 5,11,16,17,26 November

**Comment by Lynne12** [comment]
@Robinmcgvr @JackieColes @GoodallE November online scheduling is now complete.  Greece dates missing as above, unrecoverable.

**Comment by Robinmcgvr** [comment]
Manual scheduling carried out to fill gaps in Australia Prime 5-7, 16, 18 November
