### ISSUE TITLE
FRANCE ONLINE SCHEDULING GAPS MARCH 2021

### ISSUE THREAD

**Issue by Robinmcgvr** [Robinmcgvr/Online-Scheduling#12]
We have data for the following channels available from the following sources:
COVERING 16-22 MARCH 2021 (Inclusive)

programme-tv.net
AB1 (FAB1)
CINE+CLASSIC (CINF)
CINE+PREMIER (CINC)
SERIECLUB (SCLF)
TEVA (TVAF)

programme-television.org
PARAMOUNT CHANNEL (PRAF)
PARIS PREMIERE (PPRE)

**Comment by Lynne12** [comment]
@Robinmcgvr data loaded, for the above channels, 16-22 March 2021.
