### ISSUE TITLE
OCTOBER ONLINE SCHEDULING

### ISSUE THREAD

**Issue by Robinmcgvr** [Robinmcgvr/Online-Scheduling#2]
As of 02/01/2021
All October online scheduling completed
inc.
AUSTRIA
BELGIUM
CROATIA
NETHERLANDS
NEW ZEALAND
ROMANIA
SWITZERLAND
SERBIA

**Comment by Lynne12** [comment]
@Robinmcgvr can this be closed now, please.

**Comment by Robinmcgvr** [comment]
Confirming to all that October Online Scheduling is complete
