### ISSUE TITLE
DECEMBER ONLINE SCHEDULING

### ISSUE THREAD

**Issue by Robinmcgvr** [Robinmcgvr/Online-Scheduling#3]
HK SMHD prepped from Taiwan fng.tw data and emailed to you

**Comment by Robinmcgvr** [comment]
Taiwan December Fox Movies (FKA) Star Movies prepped and ready
There was nothing to enter on the other 2 channels.
I haven't emailed you this yet as I imagine Debbie is busy on verified stuff at the moment

**Comment by Lynne12** [comment]
**Countries complete:-**
 
- [x] AUSTRALIA
- [x] NEW ZEALAND
- [x] BRAZIL
- [x] MEXICO
- [x] HONG KONG
- [x] FRANCE
- [x] SPAIN
- [x] SWEDEN
- [x] GERMANY
- [x] HUNGARY
- [x] BELGIUM
- [x] NETHERLANDS
- [x] GREECE
- [x] IRELAND
- [x] PORTUGAL
- [x] SWITZERLAND
- [x] AUSTRIA
- [x] CZECH REPUBLIC
- [x] CROATIA
- [x] ROMANIA
- [x] SERBIA

**Comment by Robinmcgvr** [comment]
@Lynne12 
I wonder if it might be possible to make another tweak to the order in which these countries are worked on?
It would ,ideally, be good if those countries that also have verified channels were put nearer the top of the order, below the Latin America & Asia Pacific countries . This would mean that reports for those countries could be worked on sooner.
Is that something that could be done?

**Comment by Lynne12** [comment]
@Robinmcgvr I have reordered the list, as above.  Please confirm you are happy with this?

**Comment by Robinmcgvr** [comment]
@Lynne12 
yep that looks great, thank you!

**Comment by Robinmcgvr** [comment]
N.B. GREECE
FLMG is missing data for the following December 2020 dates:-
1,3,7,8,10

**Comment by Robinmcgvr** [comment]
Any news on when these last countries might be done?

**Comment by Robinmcgvr** [comment]
I see you have now updated Switzerland ,
 N.B. this doesn't generate me an email

**Comment by Robinmcgvr** [comment]
@Lynne12 
Romania has been unticked , was this not complete then?
It looked like it from the home page - so I went ahead with running the report.
Can you advise please?

**Comment by Robinmcgvr** [comment]
@Lynne12 
Romania has been unticked , was this not complete then?
It looked like it from the home page - so I went ahead with running the report.
Can you advise please?

**Comment by Robinmcgvr** [comment]
@Robinmcgvr 
test

**Comment by Robinmcgvr** [comment]
@Robinmcgvr 
test 2

**Comment by Lynne12** [comment]
@Robinmcgvr @Ma-rco @JackieColes @GoodallE December online scheduling is now complete.
