### ISSUE TITLE
Czech Online scheduling _ HBO

### ISSUE THREAD

**Issue by Robinmcgvr** [Robinmcgvr/Online-Scheduling#35]
HI Lynne, if we are going to go ahead with scheduling HBO czech republic, we have data available via mujtvprogram.cz
We are still waiting for confirmation of this from JB but we have data for 01/07/2022 to 30/09/2022 (which is probably going to be the initial date range) .
This all stems from a change in channels supplied to WGA , it shouldn't mean we stop processing anything.
Richard jumped the gun a bit adding you into the WGA issue, sorry about that.

**Comment by Lynne12** [comment]
@Robinmcgvr thank you for the explanation.  I will wait to hear.

**Comment by Lynne12** [comment]
@Robinmcgvr as Jonathan has pointed out this is already an online scheduling channel, so this issue can be closed.

**Comment by Robinmcgvr** [comment]
ah fine I didn't see it in the drop down box! good news then no real extra work
