### ISSUE TITLE
Ireland - RTE2 September 2020

### ISSUE THREAD

**Issue by Robinmcgvr** [Robinmcgvr/Online-Scheduling#4]
@Lynne12 
Hi Lynne,
After I sent you the email about Ireland RTE2 , I have found that actually there is a lot of data missing - seems it never got loaded.
The problem is affecting data from early hours of the 8th September for all Irish channels.
I have entered data up to the 11th for RTE2 
Perhaps this was an issue with the channel name formulations  again?
The data is all there to load via tvguide.co.uk - the preferred loading source - or via RTE.ie if there is another reason why it wouldn't load from tvguide.co,uk.
As this is quite a lot of data to manually schedule - would you be able to load Rte1 , TV3 & TG4 for 08-22  (inclusive) September please?
I started entering RTE2 data when I thought it was just a bit of data that was missing - as flagged up by Gerard's checking
So RTE2 only needs loading from the 11-22 September
I will then process it.
Thanks

**Comment by Lynne12** [comment]
@Robinmcgvr these date ranges have all been loaded from tvguide.co.uk and flagged no issues at the loading stage, so there must be an issue somewhere else.  I will try loading again.

**Comment by Robinmcgvr** [comment]
@Lynne12 
OK do you want to take that up with Richard?

**Comment by Lynne12** [comment]
Only if it is an ongoing issue?

**Comment by Robinmcgvr** [comment]
If it doesn't load this time?

**Comment by Lynne12** [comment]
No, other date ranges from September to now.  The website has been used from then until now.

**Comment by Robinmcgvr** [comment]
There must have been some kind of issue, and if it won't load now there must still be one ....?

**Comment by Lynne12** [comment]
@Robinmcgvr all channels loaded, for the date ranges requested.

**Comment by Robinmcgvr** [comment]
@Lynne12 
Great, thank you!

**Comment by Robinmcgvr** [comment]
I'll let you know when it's been processed

**Comment by Lynne12** [comment]
You can just shut the issue. I already had it marked off as complete, so there is no further action for me to take.
