### ISSUE TITLE
Portugal online scheduling NCIS v Ncis Los Angeles

### ISSUE THREAD

**Issue by Robinmcgvr** [Robinmcgvr/Online-Scheduling#42]
There is contradictory data about these two series on channel Sic portugal
Often where it says 'NCIS LA is scheduled it is actually - NCIS 
I am working to sort these out , so a word of caution on matching these.
Jackie, if you see NCIS LA in the local data text but it has an ep matched to NCIS with a series higher than 13 then the NCIS match is correct. (you may not deal with this channel in your work, but advising you if you do)
Emma knows about this , and have advised Dragana to leave ep work on this title and channel for me.

**Comment by Lynne12** [comment]
@Robinmcgvr please provide the appropriate feedback to Branko too, from the information you have gathered.

**Comment by Lynne12** [comment]
@Robinmcgvr can this be closed and a note put in to the Scheduled channel on Mattermost, so it can be viewed by all the staff that are now scheduling.

**Comment by Robinmcgvr** [comment]
I'll pin it on here for now as a reminder to me
But will put a note out on mattermost
