### ISSUE TITLE
NEW CHANNELS FOR AUSTRIA

### ISSUE THREAD

**Issue by Robinmcgvr** [Robinmcgvr/Online-Scheduling#43]
We have two new channels for AustrIa
ORF3 - tbs via tele.at (as this has data going further back - will get channel added to tv-media.at downloads going forwards)
ATV2 - tbs via tv-media.at 
It may be easier for you to load the back data for these two channels from the single source tele.at until we start getting ORF3 in the tv-media.at files 

Will confirm the dates we want to go back to once we receive the details from JB

**Comment by Lynne12** [comment]
Will wait on the dates, before taking any action on this.

**Comment by Robinmcgvr** [comment]
Have just asked JB if we want to start these from 1st September, will let you know when he gets back to me

**Comment by Robinmcgvr** [comment]
@Lynne12 
I have the go ahead now from JB to include these in the online scheduling for Austria from 01/09/2023

**Comment by Lynne12** [comment]
@Robinmcgvr you need to arrange for these channels to be set up, by Richard, on the ETS database, before I can take action on the scheduling.

**Comment by Robinmcgvr** [comment]
Oh Ok, thought you organised that, but yep I'll ask him to add the channels.

**Comment by Robinmcgvr** [comment]
That's done

**Comment by Robinmcgvr** [comment]
shall I ask him to set up the loading sources too?

**Comment by Lynne12** [comment]
I've already started that, thanks.

**Comment by Robinmcgvr** [comment]
After analysis of 2023 data for Orf3 =- this channel is going to more suited to manual scheduling
Will review ATV2 next

**Comment by Lynne12** [comment]
@Robinmcgvr can I ask in what way this is the case?  Online scheduling was set up to be quicker and we needed to move away from manual scheduling.  We seem to be getting more of this now.  Are you taking on this extra manual scheduling?  I have spent time getting this set up for online.  Maybe this should have been looked into before this happened.

**Comment by Robinmcgvr** [comment]
I know I am sorry,  JB had a hunch that Orf3 might not show many films and he was right, so it's not worth Branko's time looking for the very occasional film
ATV2 though shows a lot of films so that will still be worth online scheduling.
Yes I will do the Orf 3 Man Sched (and the Ukraine in case you were worried about that too)

**Comment by Lynne12** [comment]
Do you just require films to be scheduled for ATV2, so I can instruct Branko accordingly?

**Comment by Robinmcgvr** [comment]
Yes it will be movies only

**Comment by Lynne12** [comment]
@Robinmcgvr can this be closed now?
