### ISSUE TITLE
September week 25/09 to 01/10

### ISSUE THREAD

**Issue by Robinmcgvr** [Robinmcgvr/Online-Scheduling#46]
@Lynne12 
Please delay loading this week
Due to the kapow failure on 27th sept data for 27th and 28th is affected for some countries.
We are still recovering some of this data
We may need to use alternative sources for loading this week so that we can pick up some of the channels that may be missing from their usual source. (rather than having to plug gaps manually)
We will have a clearer picture in next couple of days and I will confirm which of the loading sites still have issues by thursday

**Comment by Lynne12** [comment]
@Robinmcgvr the week I am due to load is 19th - 25th September.  I will proceed with this, as these dates are not mentioned above.

**Comment by Lynne12** [comment]
@Robinmcgvr I would be due to load 26 Sep - 2 Oct, tomorrow.  Could you let me know when I can go ahead with this and supply a full list of the online scheduling channels affected by the missing data.

**Comment by Robinmcgvr** [comment]
@Lynne12 
It would be better to wait until thursday as I  previously said this gives Matteo more time to work on recovering data and for me to run another check.
That way the info will be more accurate.
No-one will be working on September data yet, so there isn't really a need to rush it is there?

**Comment by Lynne12** [comment]
Robin, I didn't say I was loading it.  I said it was due to be loaded and could you let me know when I can go ahead.  I am waiting on your list of missing data.

**Comment by Robinmcgvr** [comment]
great that was what I said originally

**Comment by Robinmcgvr** [comment]
@Lynne12 
Details of sites status below
Mostly OK 

[Online Country loading sites CHECKED AFTER SEPT 27 2023 FAILURE.xlsx](https://github.com/Robinmcgvr/Online-Scheduling/files/12816603/Online.Country.loading.sites.CHECKED.AFTER.SEPT.27.2023.FAILURE.xlsx)

**Comment by Lynne12** [comment]
@Robinmcgvr you missed a channel from France, SYFR.  This only has partial data for 27th.  I will load the missing data, for all channels, from 
**tv-programme.telecablesat.fr**

**Comment by Lynne12** [comment]
@Robinmcgvr as per your Excel file the gaps for PINK and PINK PREMIUM Serbia will need to be manually filled.  There is a time difference on the tv,aladin.info website and the mojtv website is a day out, compared to the usual source tvprofil.com.  These are therefore not suitable for online loading.

**Comment by Robinmcgvr** [comment]
Noted and pinned to manual scheduling page

**Comment by Lynne12** [comment]
@Robinmcgvr can this be closed now?

**Comment by Robinmcgvr** [comment]
yes
