### ISSUE TITLE
New Channel for Spain

### ISSUE THREAD

**Issue by Robinmcgvr** [Robinmcgvr/Online-Scheduling#48]
New channel for Spain =
Series por M+
Have we already incorporated this into the online scheduling?
We need data back to 01/08/2023 adding to the scheduling
The August and September can be treated as special task for me or others (might be done by Will)
But can we include it with the scheduling from October please?
I will give you the source details (most likely movistar.es) once I have checked it out

**Comment by Lynne12** [comment]
@Robinmcgvr Series por M+ is a verified channel, in Spain.
