### ISSUE TITLE
FRANCE Ô

### ISSUE THREAD

**Issue by Robinmcgvr** [Robinmcgvr/Online-Scheduling#5]
Channel has ceased - as of 24/08/2020

**Comment by Lynne12** [comment]
@Robinmcgvr this must have already been known by me, as it is no longer on our sheets to process.

**Comment by Lynne12** [comment]
@Robinmcgvr can this be closed?

**Comment by Robinmcgvr** [comment]
I would like to keep this open to remind me about if for a bit longer

**Comment by Lynne12** [comment]
@Robinmcgvr can this be closed now?
