### ISSUE TITLE
DELAY LOADING DATA COVERING PERIOD - 23/01/2024 TO 05/02/2024

### ISSUE THREAD

**Issue by Robinmcgvr** [Robinmcgvr/Online-Scheduling#52]
@Lynne12 
Due to the major software issue with Kapow last week (and ongoing) I would recommend holding off on loading data for that period as you will probably get gaps that may yet be recovered.
Australia might be ok if you were desperate to get started on it ..

**Comment by Robinmcgvr** [comment]
OK Belay that, I was being over cautious, there are some that should be OK, I'll confirm either tonight or tomorrow

ps recovery work on this is still ongoing

**Comment by Robinmcgvr** [comment]
Please also hold off on week 30/01 to 04/02
Same issues - small files , more than missing days in most cases but some sites are missing completely too

**Comment by Lynne12** [comment]
@Robinmcgvr I need a more detailed list of the issues for each website and channel that relate to online scheduling, from 23rd January up to 5h February, please.  It is getting difficult to keep track when this issue is being listed on more than one repository.

**Comment by Lynne12** [comment]
@Robinmcgvr if you could list missing dates for each website, for the individual weeks, please, so I know if there is any loading I can do:-

**Online loading week: 23-29 January 2024**

- [x] Austria   - tv-media.at-6
- [x] Australia - Albany-1 23/01 Missing
- [x] Australia - Albury-2 - 23/01 Missing
- [x] Australia - Cairns-2 - 23/01 Missing
- [x] Belgium -   moustique.be-1
- [x] Croatia -   tvhr.net-2
- [x] Croatia -   novatv.hr-1
- [x] Croatia -   rtl.hr-2 
- [x] Czech-mujtvprogram.cz-1 23/01 Missing-**loaded from idnes.cz**
- [x] France-tv-programme-television.org-6
- [x] Hong Kong -   tvb.com-1 25/01, 26/01 27/01, 29/01 Missing - _not recovered_
- [x] Ireland -   rte.ie-4
- [x] N Zealand -   sky.co.nz-2 **NSKM missing 23-29 Jan, NZ3 missing 23, 26, 28, 29**
- [x] N Zealand -   tvnz.co.nz-2
- [x] Portugal -   rtp.pt-2
- [x] Portugal -   meo.pt-2
- [x] Serbia -   tv.aladin.info-1 23/01 Missing
- [x] Serbia   -tvprofil.com-3 Pink ok, pink 2 25/01, Pink premium 25/01, 26/01, 27/01 Missing
- [x] Sweden-allente.se-3
- [x] Switzerland -   rts.ch-2 - rts1 & 2 only
- [x] Switzerland -   blue.ch-1
- [x] Switzerland -   srf.ch-3
- [x] Switzerland -   3plus.tv-3

**Comment by Lynne12** [comment]
**Online loading week: 30 January - 5 February 2024**

- [x] Austria   - tv-media.at-6
- [x] Australia - Albany-1 05/02 Missing
- [x] Australia - Albury-2 05/02 Missing
- [x] Australia - Cairns-2 05/02 Missing
- [x] Belgium -   moustique.be-1
- [x] Croatia -   tvhr.net-2
- [x] Croatia -   novatv.hr-1
- [x] Croatia -   rtl.hr-2
- [x] Czech-mujtvprogram.cz-1
- [x] France-tv-programme-television.org-6
- [x] Hong Kong -   tvb.com-1
- [x] Ireland -   rte.ie-4
- [x]  N Zealand -   sky.co.nz-2 - **NSKM missing 30&31 starts again 19.04 1/2, NZ3 missing 30&31 starts again 20.00 1/2**
- [x] N Zealand -   tvnz.co.nz-2
- [x] Portugal -   rtp.pt-2
- [x] Portugal -   meo.pt-2
- [x] Serbia -   tv.aladin.info-1
- [x] Serbia   -tvprofil.com-3 Pink 02/02, Pink Premium 31/01,01/02,02/02 Pink 2 31/01, 02/02 Missing
- [x] Sweden-allente.se-3 TV4 Hits (CSF2) switches to HD vsn from 01/02 - 05/02, TV4 Stars (CSF1) does the same (technically all days covered but not ideal), TV1000 All Ok
- [x] Switzerland -   rts.ch-2 rts1 & 2 only
- [x] Switzerland -   blue.ch-1
- [x] Switzerland -   srf.ch-3
- [x] Switzerland -   3plus.tv-3

**Comment by Robinmcgvr** [comment]
n.b rsi.ch channels available from this site not rts.ch

**Comment by Lynne12** [comment]
> n.b rsi.ch channels available from this site not rts.ch

@Robinmcgvr there has been no data on rts.ch since 15 January for the RSI channels.  Shall I make a permanent switch to rsi.ch?  Just a heads up there is a couple of hours difference in the data, so there may be some overlaps if/when we first change.

**Comment by Robinmcgvr** [comment]
Yes please, sounds like the best idea

**Comment by Lynne12** [comment]
@Robinmcgvr Sweden allente.se - Is the switch to HD for CSF1 and CSF2 likely to be permanent?

**Comment by Robinmcgvr** [comment]
I don't know, for sure, but it's most likely as Matteo has had to rebuild the robot and it is now taking these versions instead. It's probably easier to carry on with these channels than ask him to switch them back.

**Comment by Lynne12** [comment]
@Robinmcgvr there was more of the data missing for New Zealand, NSKM and NZ3 than previously thought.  I have highlighted the channels and dates in the full lists above.

**Comment by Lynne12** [comment]
@Robinmcgvr can this be closed now?

**Comment by Lynne12** [comment]
> @Robinmcgvr can this be closed now?
