### ISSUE TITLE
JANUARY ONLINE SCHEDULING 

### ISSUE THREAD

**Issue by Robinmcgvr** [Robinmcgvr/Online-Scheduling#6]
@Lynne12 
I think it would be a good idea to refrain from attempting to load any data covering the period 23-25 Jan until myself and Matteo have finished the work we are doing on this.
This would save you time and effort reporting and logging missing data, when Matteo and myself are doing the same thing.
I am working on populating the online scheduling list with the info re what's lost and what's not.
I have seen a couple that haven't been restored that could be, as the sites do allow us to go back, so I will alert Matteo to these

**Comment by Lynne12** [comment]
I haven't done so, with the exception of Netherlands, where data was fully available for this period.

**Comment by Lynne12** [comment]
Countries complete:-

- [x]  AUSTRALIA
- [x] NEW ZEALAND
- [x] BRAZIL
- [x] MEXICO
- [x]  HONG KONG
 - [x] FRANCE
 - [x] SPAIN
- [x]  SWEDEN
- [x]  GERMANY
- [x]  HUNGARY
 - [x] BELGIUM
 - [x] NETHERLANDS
 - [x] GREECE
- [x]  IRELAND
 - [x] PORTUGAL
- [x]  SWITZERLAND
- [x]  AUSTRIA
- [x]  CZECH REPUBLIC
- [x]  CROATIA
- [x]  ROMANIA
 - [x] SERBIA

**Comment by Robinmcgvr** [comment]
@Lynne12 
Hong Kong Star Movies Translations file prepped and emailed
N.B. Also Taiwan

**Comment by Robinmcgvr** [comment]
One question re. Greece - are we carrying on scheduling until we either get the verified data in or until the two catch up with each other?

**Comment by Lynne12** [comment]
> One question re. Greece - are we carrying on scheduling until we either get the verified data in or until the two catch up with each other?

Jonathan will need to answer this for you.

**Comment by Lynne12** [comment]
@Robinmcgvr @JackieColes @GoodallE January online scheduling is now complete.
