### ISSUE TITLE
February online scheduling

### ISSUE THREAD

**Issue by Lynne12** [Robinmcgvr/Online-Scheduling#7]
Countries complete:-

- [x] AUSTRALIA
- [x] NEW ZEALAND
- [x] BRAZIL
- [x] MEXICO
- [x] HONG KONG
- [x] FRANCE
- [x] SPAIN
- [x] SWEDEN
- [x] GERMANY
- [x] HUNGARY
- [x] BELGIUM
- [x] NETHERLANDS
- [x] GREECE (With the exception of FLMG missing 14th-18th)
- [x] IRELAND
- [x] PORTUGAL
- [x] SWITZERLAND
- [x] AUSTRIA
- [x] CZECH REPUBLIC
- [x] CROATIA
- [x] ROMANIA
- [x] SERBIA

**Comment by Robinmcgvr** [comment]
HK STAR MOVIES TRANSLATIONS PREPPED AND EMAILED

**Comment by Lynne12** [comment]
@Robinmcgvr @JackieColes @GoodallE @Ma-rco February online scheduling is now complete.
