### ISSUE TITLE
March 2021 online scheduling

### ISSUE THREAD

**Issue by Robinmcgvr** [Robinmcgvr/Online-Scheduling#8]
HK STAR MOVIES HD TRANSLATIONS PREPPED AND EMAILED

**Comment by Lynne12** [comment]
Countries complete:-
 
- [x] AUSTRALIA
- [x]  NEW ZEALAND
- [x]  HONG KONG
- [x]  FRANCE 
- [x] SPAIN
- [x]  SWEDEN
- [x]  GERMANY
- [x]  HUNGARY
- [x]  BELGIUM
- [x]  NETHERLANDS
- [x]  GREECE - FLMG ONLY (NOVA CINEMA 1)
- [x]  IRELAND
- [x]  PORTUGAL
 - [x] SWITZERLAND
- [x]  AUSTRIA
- [x]  CZECH REPUBLIC
- [x]  CROATIA
- [x]  ROMANIA
- [x]  SERBIA

**Comment by Robinmcgvr** [comment]
@Lynne12 
I have some time today, I could do some of this scheduling if you like?

**Comment by Lynne12** [comment]
@Robinmcgvr that would be good, thanks.  Could you go with Romania, please.  No channels have been started.  If you let me have an update on here, at end of day.

**Comment by Robinmcgvr** [comment]
okey dokey - will do

**Comment by Robinmcgvr** [comment]
I have done TVR1, TVR1, PRO TV AND ANTENA 1
Should be Ok to carry on tomorrow

**Comment by Lynne12** [comment]
Thanks @Robinmcgvr .  Did you mean TVR1 & TVR2?

**Comment by Robinmcgvr** [comment]
I did yes

**Comment by Robinmcgvr** [comment]
Romania all done

**Comment by Robinmcgvr** [comment]
TSR2 done

**Comment by Lynne12** [comment]
@Robinmcgvr @JackieColes @GoodallE @Ma-rco March online scheduling is now complete.

**Comment by Robinmcgvr** [comment]
There was france data missing from Mach probably from the data issue , but there was a source to load from and this probably should have been used e.g. Teva 18/03/2021
